Lock sprockets-rails due to v3.0.0 nil assets:
NoMethodError: undefined method `append_path' for nil:NilClass
/home/travis/.rvm/gems/ruby-2.1.5/gems/opal-rails-0.8.0/lib/opal/rails/engine.rb:34:in `block in <class:Engine>'